"""Project-local UI launcher generation and its project-root link.

The launcher is a machine-local convenience: it starts the standalone browser UI
for one project with that project's own runtime root and port, and stops the
whole process group again so the private stdio server it started cannot leak.
Nothing here reads or writes corpus state, and nothing here mutates a generation.
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Any

LAUNCHER_DIRECTORY = "bin"
LAUNCHER_NAME = "open-ui.sh"
LINK_NAME = "open-ui.sh"
LINK_TARGET = f".research-rag/{LAUNCHER_DIRECTORY}/{LAUNCHER_NAME}"
DEFAULT_UI_PORT = 5051
UI_COMMAND = "research-ultra-rag-ui"


def default_ui_command() -> str:
    """Return the UI command to embed, preferring the running environment.

    A launcher is run from a user shell, where the console script a server was
    installed with is usually absent from `PATH`, so an absolute sibling of the
    running interpreter is preferred over the bare name.
    """

    if sys.executable:
        sibling = Path(sys.executable).parent / UI_COMMAND
        if sibling.is_file() and os.access(sibling, os.X_OK):
            return str(sibling)
    return shutil.which(UI_COMMAND) or UI_COMMAND


_TEMPLATE = """#!/bin/sh
# Generated by research-ultra-rag-mcp for the @PROJECT_NAME@ project.
#
#   open-ui.sh                 start the browser UI for this project
#   open-ui.sh --open          start it and open it in the browser
#   open-ui.sh --stop          stop it, and the private server it started
#   open-ui.sh --port NUMBER   start it on a different port
#   open-ui.sh --help          show this text
#
# Machine-local by design: the project's own .gitignore should keep it out of Git.
set -eu

PROJECT_ROOT="@PROJECT_ROOT@"
STATE_ROOT="@STATE_ROOT@"
RUNTIME_ROOT="@RUNTIME_ROOT@"
PORT=@PORT@
UI_COMMAND="@UI_COMMAND@"

PID_FILE="$STATE_ROOT/open-ui.pid"
PORT_FILE="$STATE_ROOT/open-ui.port"
LOG_FILE="$STATE_ROOT/logs/open-ui.log"
LOCK_DIR="$STATE_ROOT/open-ui.lock"
# 0.25s steps: how long a launcher waits for another one that is choosing a port.
LOCK_WAIT=40
# Attempts at finding a port that this project's UI can actually bind.
LAUNCH_ATTEMPTS=5
# The interpreter beside the UI command speaks Python; the port scan needs it.
PYTHON="$(dirname "$UI_COMMAND")/python3"
[ -x "$PYTHON" ] || PYTHON=python3
OPEN_BROWSER=0
PORT_EXPLICIT=0

usage() {
  cat <<'TEXT'
Usage: open-ui.sh [--open] [--stop] [--port NUMBER] [--help]

  (no option)    start the browser UI for this project and print its URL
  --open         start it and open it in the browser
  --stop         stop it, and the private stdio server it started
  --port NUMBER  start it on a different port
  --help         show this text

Without --port the launcher starts on the first free port at or above the one it
was generated with, so two projects never serve their UI from the same port.
TEXT
}

running_pid() {
  [ -f "$PID_FILE" ] || return 1
  pid=$(cat "$PID_FILE" 2>/dev/null || true)
  [ -n "$pid" ] || return 1
  kill -0 "$pid" 2>/dev/null || return 1
  printf '%s' "$pid"
}

serving_port() {
  cat "$PORT_FILE" 2>/dev/null || printf '%s' "$PORT"
}

free_port() {
  # The first free port at or above the requested one. A second project's
  # launcher must never take a port another project's UI is already serving on,
  # because opening that URL would show the wrong project.
  "$PYTHON" -c "import socket, sys
for candidate in range(int(sys.argv[1]), int(sys.argv[1]) + 100):
    try:
        with socket.socket() as probe:
            probe.bind(('127.0.0.1', candidate))
        print(candidate)
        break
    except OSError:
        continue" "$1" 2>/dev/null || printf '%s' "$1"
}

open_url() {
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "http://127.0.0.1:$PORT" >/dev/null 2>&1 || true
  else
    echo "Open http://127.0.0.1:$PORT in your browser."
  fi
}

take_lock() {
  # mkdir is atomic, so two launchers can never both be choosing a port. A lock
  # whose writer is gone is not a claim either: that is what a killed launcher
  # leaves behind.
  waited=0
  while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    owner=$(cat "$LOCK_DIR/pid" 2>/dev/null || true)
    if [ -n "$owner" ] && ! kill -0 "$owner" 2>/dev/null; then
      rm -rf "$LOCK_DIR"
      continue
    fi
    if [ "$waited" -ge "$LOCK_WAIT" ]; then
      echo "Another launcher is choosing a port for this project; try again." >&2
      exit 1
    fi
    sleep 0.25
    waited=$((waited + 1))
  done
  printf '%s' "$$" > "$LOCK_DIR/pid"
  trap 'rm -rf "$LOCK_DIR"' EXIT INT TERM
}

launch() {
  # One attempt on the current PORT. The child leads its own session, so a later
  # --stop can signal the UI and everything the UI starts below it.
  mkdir -p "$STATE_ROOT/logs"
  if [ -n "$RUNTIME_ROOT" ]; then
    if command -v setsid >/dev/null 2>&1; then
      setsid "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        --runtime-root "$RUNTIME_ROOT" --port "$PORT" >>"$LOG_FILE" 2>&1 &
    else
      "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        --runtime-root "$RUNTIME_ROOT" --port "$PORT" >>"$LOG_FILE" 2>&1 &
    fi
  else
    if command -v setsid >/dev/null 2>&1; then
      setsid "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        --port "$PORT" >>"$LOG_FILE" 2>&1 &
    else
      "$UI_COMMAND" --project-root "$PROJECT_ROOT" \\
        --port "$PORT" >>"$LOG_FILE" 2>&1 &
    fi
  fi
  CANDIDATE=$!
  sleep 1
  kill -0 "$CANDIDATE" 2>/dev/null
}

start() {
  if pid=$(running_pid); then
    echo "The UI is already running for this project (pid $pid)."
    echo "URL: http://127.0.0.1:$(serving_port)"
  else
    take_lock
    attempts=0
    started=0
    while [ "$attempts" -lt "$LAUNCH_ATTEMPTS" ]; do
      attempts=$((attempts + 1))
      if [ "$PORT_EXPLICIT" = "0" ]; then
        PORT="$(free_port "$PORT")"
      fi
      if launch; then
        started=1
        break
      fi
      # The UI exited straight away. Probing for a free port and binding it are
      # two steps, so another process can take the port in between and leave this
      # attempt as the loser: take the next port rather than leave the project
      # without a UI. An explicit --port is the caller's choice, so it is final.
      if [ "$PORT_EXPLICIT" = "1" ]; then
        break
      fi
      PORT=$((PORT + 1))
    done
    if [ "$started" != "1" ]; then
      rm -rf "$LOCK_DIR"
      echo "The UI did not stay up; read $LOG_FILE" >&2
      exit 1
    fi
    # Recorded only once the UI is known to be running, so a failed attempt
    # cannot leave a pid or a port file naming something that is not there.
    printf '%s' "$PORT" > "$PORT_FILE"
    printf '%s' "$CANDIDATE" > "$PID_FILE"
    rm -rf "$LOCK_DIR"
    echo "Started the UI for this project (pid $CANDIDATE)."
    echo "URL: http://127.0.0.1:$PORT"
    echo "Log: $LOG_FILE"
  fi
  if [ "$OPEN_BROWSER" = "1" ]; then
    open_url
  fi
}

owns_project() {
  # Without /proc to read, the pid file is all there is to go on.
  [ -r "/proc/$1/cmdline" ] || return 0
  tr '\\0' ' ' < "/proc/$1/cmdline" | grep -F -- "$PROJECT_ROOT" >/dev/null 2>&1
}

sweep_servers() {
  # A private server busy in a long build does not read stdin until the phase it
  # is in returns, so it can outlive the UI that started it. The CLI's own sweep
  # names this project and is a no-op when nothing is left; a missing entry point
  # must not fail a stop.
  SWEEP="$(dirname "$UI_COMMAND")/research-ultra-rag"
  [ -x "$SWEEP" ] || return 0
  "$SWEEP" --project-root "$PROJECT_ROOT" stop --servers >>"$LOG_FILE" 2>&1 || true
}

stop() {
  if ! pid=$(running_pid); then
    rm -f "$PID_FILE"
    echo "No UI is running for this project."
    return 0
  fi
  if ! owns_project "$pid"; then
    # A pid file outlives its process and the number can be reused, and a port
    # file can name another project's port when two launchers raced. Neither is a
    # reason to signal a process that is not this project's UI.
    rm -f "$PID_FILE" "$PORT_FILE"
    echo "Pid $pid is not this project's UI; left it alone." >&2
    return 0
  fi
  # The UI starts a private stdio server and its UltraRAG gateway below it, so
  # stop the whole process group rather than only the launcher's own child. The
  # private server keeps a session of its own, which is why a server that was
  # still busy when the UI died is swept separately afterwards.
  kill -TERM "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
  waited=0
  while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt 20 ]; do
    sleep 0.25
    waited=$((waited + 1))
  done
  if kill -0 "$pid" 2>/dev/null; then
    kill -KILL "-$pid" 2>/dev/null || kill -KILL "$pid" 2>/dev/null || true
  fi
  rm -f "$PID_FILE"
  sweep_servers
  echo "Stopped the UI for this project (pid $pid)."
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --open) OPEN_BROWSER=1 ;;
    --stop) stop; exit 0 ;;
    --port)
      [ "$#" -ge 2 ] || { echo "--port needs a number" >&2; exit 2; }
      PORT="$2"
      PORT_EXPLICIT=1
      shift
      ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

if [ ! -d "$PROJECT_ROOT" ]; then
  echo "Project root is missing: $PROJECT_ROOT" >&2
  exit 1
fi
start
"""


def launcher_path(portable_root: Path) -> Path:
    """Return the generated launcher's location inside the project."""

    return portable_root / LAUNCHER_DIRECTORY / LAUNCHER_NAME


def link_path(project_root: Path) -> Path:
    """Return the project-root link to the generated launcher."""

    return project_root / LINK_NAME


def launcher_script(
    *,
    project_root: Path,
    state_root: Path,
    project_name: str,
    port: int = DEFAULT_UI_PORT,
    runtime_root: Path | None = None,
    ui_command: str | None = None,
) -> str:
    """Render the launcher for one project."""

    return (
        _TEMPLATE.replace("@PROJECT_NAME@", project_name)
        .replace("@PROJECT_ROOT@", str(project_root))
        .replace("@STATE_ROOT@", str(state_root))
        .replace("@RUNTIME_ROOT@", str(runtime_root) if runtime_root else "")
        .replace("@PORT@", str(port))
        .replace("@UI_COMMAND@", ui_command or default_ui_command())
    )


def _link_state(link: Path) -> str:
    if link.is_symlink():
        return "linked" if os.readlink(link) == LINK_TARGET else "foreign_link"
    if link.exists():
        return "foreign_file"
    return "absent"


def ensure_ui_launcher(
    *,
    project_root: Path,
    portable_root: Path,
    state_root: Path,
    project_name: str,
    port: int = DEFAULT_UI_PORT,
    runtime_root: Path | None = None,
    ui_command: str | None = None,
) -> dict[str, Any]:
    """Create the launcher and its project-root link when they are absent.

    An existing launcher or project-root entry is never overwritten, so a user
    edit survives. Failures are reported rather than raised: the launcher is a
    convenience and must never stop the server from starting.
    """

    script = launcher_path(portable_root)
    link = link_path(project_root)
    script_state = "present"
    note: str | None = None
    try:
        script.parent.mkdir(parents=True, exist_ok=True)
        if not script.exists():
            temporary = script.with_name(f".{script.name}.tmp")
            temporary.write_text(
                launcher_script(
                    project_root=project_root,
                    state_root=state_root,
                    project_name=project_name,
                    port=port,
                    runtime_root=runtime_root,
                    ui_command=ui_command,
                ),
                encoding="utf-8",
                newline="\n",
            )
            temporary.chmod(0o755)
            os.replace(temporary, script)
            script_state = "created"
    except OSError as exc:
        return {
            "script_path": str(script),
            "link_path": str(link),
            "link_target": LINK_TARGET,
            "script_state": "unavailable",
            "link_state": _link_state(link),
            "note": str(exc),
        }
    link_state = _link_state(link)
    try:
        if link_state == "absent":
            link.symlink_to(LINK_TARGET)
            link_state = "linked"
        elif link_state != "linked":
            note = (
                "The project root already has an open-ui.sh that this server did "
                "not create; it was left untouched."
            )
    except OSError as exc:
        link_state = "unavailable"
        note = str(exc)
    return {
        "script_path": str(script),
        "link_path": str(link),
        "link_target": LINK_TARGET,
        "script_state": script_state,
        "link_state": link_state,
        "note": note,
    }


def ui_launcher_state(project_root: Path, portable_root: Path) -> dict[str, Any]:
    """Report the launcher and its link without changing anything."""

    script = launcher_path(portable_root)
    link = link_path(project_root)
    link_state = _link_state(link)
    if link_state == "linked" and not script.is_file():
        link_state = "broken_link"
    return {
        "script_path": str(script),
        "script_present": script.is_file(),
        "link_path": str(link),
        "link_target": LINK_TARGET,
        "link_state": link_state,
        "default_port": DEFAULT_UI_PORT,
        "note": (
            "The launcher starts the standalone browser UI for this project and "
            "stops its private server with --stop. It is machine-local; keep it "
            "out of version control. It takes --open, --stop, and --port."
        ),
    }
